### PR TITLE
fix: file path parsing in sany output

### LINKED ISSUE #329: Coverage has blank Action on both Nightly and TLA+ Foundation's TLA+ VScode, Alygin's version is OK.
It shows like this in both Nightly and TLA+ Foundation's:
TLA+VScodeErrorReport

This is shows fine in Alygin's.
TLA+VScodePassReport

Thanks,
Zitro

### PR DESCRIPTION
**Pull request by afonsonf**
# Changes
* Fixes file path parsing in sany output
    * In windows line is as follows: `Parsing file C:\Users\Afonso\CPlusCal.tla (file:/c:/Users/Afonso/CPlusCal.tla)`
    * In Linux line is as follows: `Parsing file /workspaces/folder/CPlusCal.tla`
    * Custom sany parser expects line to end with `(jar:file:.*)` or nothing, changed to expect `(.*)` or nothing
* In case filepath or changes range are null show action name instead of null
* Remove files property from package json as that information is present in `.vscodeignore` file and having both causes vsce to not work with following error
    *  `ERROR  Both a .vscodeignore file and a "files" property in package.json were found. VSCE does not support combining both strategies. Either remove the .vscodeignore file or the "files" property in package.json.`

Fixes #329

### CODE REVIEW

File: src/parsers/sany.ts [hunk 1]
```diff
@@ -248,7 +248,7 @@ export class SanyStdoutParser extends ProcessOutputHandler<SanyData> {
     }
 
     private tryParseModulePath(line: string) {
-        const rxJarPath = /^(.*)(?: \(jar:file:.*\))$/g;
+        const rxJarPath = /^(.*)(?: \(.*\))$/g;
```
Comment (lemmy) [inline src/parsers/sany.ts:251]: Does it make sense to change the name of the const to something other than `rxJarPath` given that the regex has been relaxed?

**Review by lemmy — APPROVED** [review]

File: src/parsers/sany.ts (hunk 1 above)
Comment (afonsonf) [reply src/parsers/sany.ts]: Good point, updated, thanks

**Comment by afonsonf** [comment]
Can you merge the PR @lemmy ? Thanks

**Comment by lemmy** [comment]
Done.

I assumed that you have the necessary permissions. Will correct asap.
