### PR TITLE
fix: prevent incorrect navigation on record field names (#383)

### LINKED ISSUE #383: When using Ctrl+Click on `bar` within the record definition, it incorrectly navigates to the definition of `bar`.
> I just realized there's a bug in our VSCode extension: when using Ctrl+Click on `bar` within the record definition, it incorrectly navigates to the definition of `bar`.
> 
> https://github.com/user-attachments/assets/2fde27fb-aeea-4c94-a039-ba9ee1cbde55 

> I'm uncertain whether this specific issue should be addressed directly, as it may stem from a broader set of bugs and inconsistencies caused by the VSCode extension relying on a custom, incomplete parser. It might be more effective to refactor the extension to use the SANY parser instead. Some initial work on this refactor has already begun, as seen in https://github.com/tlaplus/vscode-tlaplus/commit/c2946bf87c0228a355e49b3f83b579eb554935e4.

 _Originally posted by @lemmy in [#377](https://github.com/tlaplus/vscode-tlaplus/issues/377#issuecomment-2869219451)_

### PR DESCRIPTION
**Pull request by younes-io**
Fixes #383 - Ctrl+clicking on field names in record definitions incorrectly navigated to variables with the same name.

  - Field names in record definitions: [bar |-> value]
  - Field names in record access: state.bar
  - Field names in EXCEPT expressions: [state EXCEPT !.bar = ...]

### CODE REVIEW

**Comment by younes-io** [comment]
Test file:

```tla
---- MODULE TestIssue383Complete ----
EXTENDS Integers

VARIABLES bar, state, x

RecordDef == [bar |-> 1, baz |-> 2]

Init == /\ state = [bar |-> 0, value |-> 10]
        /\ x = 5
        /\ bar = 100

GetBar == state.bar

UseBar == bar + 1

Next == state' = [state EXCEPT !.bar = state.bar + 1]

MultipleRecords == 
    /\ [bar |-> 1, x |-> 2]
    /\ [first |-> bar, second |-> x]

====

```

File: src/declarations/tlaDeclarations.ts [hunk 1]
```diff
@@ -6,7 +6,35 @@ function symbolLocations(document: vscode.TextDocument, docInfo: TlaDocumentInfo
...
+        return undefined;
+    }
+
+    // Check if the word is preceded by "!." which would indicate it's in an EXCEPT expression
+    if (range.start.character > 1 && line.substring(range.start.character - 2, range.start.character) === '!.') {
+        // This is a record field in EXCEPT expression (e.g., [state EXCEPT !.x = ...])
+        return undefined;
+    }
+
+    // Check if this is a field name in a record definition (e.g., [bar |-> value])
```
Comment (lemmy) [inline src/declarations/tlaDeclarations.ts:23]: Same question as in https://github.com/tlaplus/vscode-tlaplus/pull/382#discussion_r2129524036

Comment (younes-io) [reply src/declarations/tlaDeclarations.ts:23]: was actually working on this case

**Comment by younes-io** [comment]
EDIT: 
Updated the test file with multiline records https://github.com/tlaplus/vscode-tlaplus/pull/384#issuecomment-2946370435
