### PR TITLE
Parse pluscal labels inserted due to macro

### LINKED ISSUE #352: "Show inserted labels" diagnostics don't work when a label is inserted via macro
## Description:

image

### Steps to reproduce:

1. In the settings file, set `"tlaplus.pluscal.options": "-reportLabels"`,
2. Translate the following algorithm:

```
(*--algorithm alg {
variable x = 1;
macro inc() {
    x := x + 1;
}
process (hello = 1) {
    x := x + 1;
    x := x + 1;
    inc();
    x := x + 1;
    x := x + 1;
}

} *)
```

### Expectations:

Diagnostics should underline all five lines, showing that five labels were inserted. But diagnostics stop after the second label.

### Cause:

The problem is this line in the PlusCal parser:

https://github.com/tlaplus/vscode-tlaplus/blob/a3169adfa37ffad0ae630f49247db6f29f7479be/src/parsers/pluscal.ts#L127-L131

This matches regular labels, but labels inserted from macros have a different format:

```
The following labels were added:
  Lbl_1 at line 11, column 5
  Lbl_2 at line 12, column 5
  Lbl_3 at line 8, column 5 of macro called at line 13, column 5
  Lbl_4 at line 14, column 5
  Lbl_5 at line 15, column 5
```

So the label parser terminates early and doesn't label the macro or any lines past the macro.

### Notes:

Go ahead and assign this to me, I can fix it next week

### PR DESCRIPTION
**Pull request by hwayne**
Fixes #352 

image

Since parsing rules for label insertions due to macros are slightly different than parsing any other location in the translation output, I figured it would work best to add a separate `parseLabelLocation` method with different rules. See docstring for an explanation as to differences.

### CODE REVIEW

File: src/parsers/pluscal.ts [hunk 1]
```diff
@@ -124,21 +125,25 @@ export class TranspilerStdoutParser extends ProcessOutputHandler<DCollection> {
             return false;
         }
 
-        const matcher = /^\s\s([A-Za-z0-9_]+) at line \d+, column \d+$/g.exec(line);
+        const matcher = /^\s\s([A-Za-z0-9_]+) at line \d+, column \d+/g.exec(line);
```
Comment (hwayne) [inline src/parsers/pluscal.ts:128]: Note the removal of the `$` at the end, so it will match as long as the string has `matcher` as a prefix. This is only called if we're in `label parsing mode` so won't affect parsing any other output.

**Comment by hwayne** [comment]
Also, I checked procedure label insertion just to be sure. They work fine.

**Review by FedericoPonzi — APPROVED** [review]
LGTM, thanks!

**Comment by hwayne** [comment]
Comment moved, ready to merge!
