### PR TITLE
PDF Generation: feature parity with the toolbox

### LINKED ISSUE #348: Generating PDF does not gray shade comments
## Description:
In the ToolBox, this what it looks like generating PDF.
image
 But in VScode, this what it looks like generating the same PDF.
image

### Steps to reproduce:
In VSCode command palette execute TLA+ Export module to PDF

### Expectations:
I expect the same comment to appear with gray shading as in the ToolBox.

### Version Information:
* Plugin Version: v2024.10.302302
* OS: Windows 11

### PR DESCRIPTION
**Pull request by FedericoPonzi**
Fixes #348.
Adds few options to the plugin, lifted from https://github.com/tlaplus/tlaplus/blob/ab14a33e39c78e4c88e81b664b9a8c916b943cab/toolbox/org.lamport.tla.toolbox.tool.tla2tex/src/org/lamport/tla/toolbox/tool/tla2tex/handler/ProducePDFHandler.java#L106:

image

This is with comment shade option checked:
image

With shade of 0.2:
image

With the numbered option:
image

With no pcal shade unchecked:
image

With nopcal shade checked:
image

### CODE REVIEW

File: src/webview/checkResultView/headerSection/index.tsx [hunk 1]
```diff
@@ -34,7 +34,8 @@ export const HeaderSection = React.memo(({checkResult}: HeaderSectionI) => {
                 <span hidden={checkResult.state !== 'R'}>
                     (<VSCodeLink onClick={vscode.stopProcess} href="#"> stop </VSCodeLink>)
                 </span>
-                <span hidden={ checkResult.statusDetails === undefined || checkResult.statusDetails === null}>: {' ' + checkResult.statusDetails} </span>
```
Comment (FedericoPonzi) [inline src/webview/checkResultView/headerSection/index.tsx:37]: unrelated change, making eslint happy

File: src/tla2tools.ts [hunk 2]
```diff
@@ -148,6 +181,8 @@ async function runTool(
     toolOptions: string[],
     javaOptions: string[]
 ): Promise<ToolProcessInfo> {
+    // log the arugments:
+    //console.log(toolName + ': ' + filePath + ' ' + toolOptions.join(' ') + ' ' + javaOptions.join(' '));
```
Comment (lemmy) [inline src/tla2tools.ts:185]: Should this be commented?

File: src/tla2tools.ts [hunk 3]
```diff
@@ -101,11 +105,40 @@ export async function runSany(tlaFilePath: string): Promise<ToolProcessInfo> {
     );
 }
 
+function buildTexOptions(tlaFilePath: string, shadeComments: boolean, commentColor: number, numberLines: boolean, noPcalShade: boolean): string[] {
+    const toolArgs = ['-metadir',
+        path.dirname(tlaFilePath),
```
Comment (lemmy) [inline src/tla2tools.ts:110]: `-metadir path.dirname(tlaFilePath)` seems new.  Why is it needed?

File: src/tla2tools.ts (hunk 2 above)
Comment (FedericoPonzi) [reply src/tla2tools.ts:185]: I meant to leave it there commented for debugging, but can also just remove it

Comment (lemmy) [reply src/tla2tools.ts:185]: No need to remove it.

File: src/tla2tools.ts (hunk 3 above)
Comment (FedericoPonzi) [reply src/tla2tools.ts:110]: It is used [here](https://github.com/tlaplus/tlaplus/blob/ab14a33e39c78e4c88e81b664b9a8c916b943cab/toolbox/org.lamport.tla.toolbox.tool.tla2tex/src/org/lamport/tla/toolbox/tool/tla2tex/handler/ProducePDFHandler.java#L135C1-L135C34):
```
					tla2texArgs.add("-metadir");
					tla2texArgs.add(fileToTranslate.getProject().getLocation()
							.toOSString());
```
and wanted to port it here as well.
According to [TLC](https://github.com/tlaplus/tlaplus/blob/9fc01661b60af2db3077ed5060fa514c9c9d40cf/tlatools/org.lamport.tlatools/src/tlc2/TLC.java#L1608):
```
"-metadir"
"specify the directory in which to store metadata; defaults to SPEC-directory/states if not specified"
```
I guess it's fine to omit it? I also noticed I forgot to add TLA2TeX_Output_Extension, but I'm not sure if it's really needed, what do you think?

Comment (lemmy) [reply src/tla2tools.ts:110]: Sorry, I don't remember if tla2tex creates temporary files.

Comment (FedericoPonzi) [reply src/tla2tools.ts]: Removed for now, we can add it later if needed be (doesn't seem to make any difference as far as I can tell)
